import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr.size)
print(arr.shape)
print("Flattened Array:")
print(arr.flatten())
arr2 = arr.reshape(3, 3, 1)
print("Reshaped Array (3, 3, 1):")
print(arr2) 
m= np.matrix(arr2)
m2= np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix Representation:")
print(m2)
print("Matrix Multiplication Result:")
print(m * m2)
print(m.max())